### ISSUE TITLE
Resource Name

### ISSUE THREAD

**Issue by ArieHein** [ndriscol/RemoteConnectivityPermissionsDSC#3]
From the name of the resource its not obvious what the resource is about, perhaps renaming it
as DCOMSecurityDSC might be more suitable ?

**Comment by ndriscol** [comment]
I'm currently writing a resource for permissioning wmimgmt, which I wanted to release together. Maybe there is a better name overall?

**Comment by ArieHein** [comment]
Do you set the wmimgmt permissions from the same UI you set the DCOM ones ? 
I dont remember so, in which case i'd separate it to two distinct resources.
DCOMSecurityDSC and WMISecurityDSC  ?

**Comment by ndriscol** [comment]
Cool, I'll rename the resource.

**Comment by ndriscol** [comment]
Uploaded resources with new suitable name as dicussed
